import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HistorySideBar from "../features/history/HistorySidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
 


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex min-h-screen flex-col">
        <SidebarProvider>
          <div className="flex flex-1">
            <HistorySideBar />
            <div className="flex-1 flex flex-col">
              {/* This trigger toggles sidebar collapse */}
              <SidebarTrigger className="p-2" />
              <main className="flex-1 p-4">
                <>{children}</>
              </main>
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
