OPEN_AI_GPT_4_1_MINI = "gpt-4.1-mini"
OPEN_AI_GPT_4_1_NANO = "gpt-4.1-nano"

ALLOWED_OPENAI_MODELS = [
    OPEN_AI_GPT_4_1_MINI,
    OPEN_AI_GPT_4_1_NANO,
]

DEFAULT_OPENAI_MODEL_NAME = OPEN_AI_GPT_4_1_NANO
MAX_OUTPUT_TOKENS = 2000

DEFAULT_TEMPERATURE = 1
DEFAULT_TOP_P = 1.0
DEFAULT_MAX_TOKENS = 500
